# Stage 1: Builder
FROM python:3.9-slim as builder
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev gcc
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Stage 2: Final Image
FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /root/.local /root/.local
COPY scripts/ /app/scripts/

ENV PATH=/root/.local/bin:$PATH
ENTRYPOINT ["python", "/app/scripts/etl_script.py"]